### ISSUE TITLE
Getting "Instructor does not support multiple tool calls, use List[Model] instead"

### ISSUE THREAD

**Issue by gianx89** [BrainBlend-AI/atomic-agents#30]
Especially using local models I often get the following error:

**AssertionError: Instructor does not support multiple tool calls, use List[Model] instead**

Could be related to [https://github.com/instructor-ai/instructor/issues/840](https://github.com/instructor-ai/instructor/issues/840) ?

```
Traceback (most recent call last):
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/instructor/retry.py", line 195, in retry_sync
    return process_response(
           ^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/instructor/process_response.py", line 153, in process_response
    model = response_model.from_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/instructor/function_calls.py", line 152, in from_response
    return cls.parse_tools(completion, validation_context, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/instructor/function_calls.py", line 336, in parse_tools
    len(message.tool_calls or []) == 1
AssertionError: Instructor does not support multiple tool calls, use List[Model] instead

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/instructor/retry.py", line 189, in retry_sync
    for attempt in max_retries:
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1391c93d0 state=finished raised AssertionError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gianx89/PycharmProjects/atomic-agents/project/project/rag/answer_agent.py", line 224, in <module>
    main()
  File "/Users/gianx89/PycharmProjects/atomic-agents/project/project/rag/answer_agent.py", line 216, in main
    response = agent.run(BaseAgentInputSchema(chat_message=user_input))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/atomic_agents/agents/base_agent.py", line 124, in run
    response = self.get_response(response_model=self.output_schema)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/atomic_agents/agents/base_agent.py", line 106, in get_response
    response = self.client.chat.completions.create(model=self.model, messages=messages, response_model=response_model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/instructor/client.py", line 119, in create
    return self.create_fn(
           ^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/instructor/patch.py", line 291, in new_create_sync
    response = retry_sync(
               ^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/atomic-agents/.venv/lib/python3.11/site-packages/instructor/retry.py", line 227, in retry_sync
    raise InstructorRetryException(
instructor.exceptions.InstructorRetryException: Instructor does not support multiple tool calls, use List[Model] instead

Process finished with exit code 1
```

**Comment by gianx89** [comment]
For the current model (yi-coder-9b-chat through lmstudio) I solved like this:

```
    client = instructor.from_openai(
        OpenAI(
            base_url="http://localhost:11434/v1",
            api_key="ollama",
        ),
        mode=instructor.Mode.MD_JSON
    )
```

I'll have to add this to the output instructions (sometimes I got invalid JSON as response):

```
output_instructions=[
    "Your response must be a valid JSON."
]
```

I'll reopen the issue if needed.

**Comment by ieea** [comment]
Hi Kenny,
I tried as per the suggestion, but still issue is not resolved.


        client = instructor.from_openai(openai.OpenAI(base_url="http://localhost:11434/v1", api_key="ollama")),
        mode=instructor.Mode.MD_JSON,
        model = "llama3.2:latest",


Please re-open the issue, and help me resolve the same.

**Comment by gianx89** [comment]
@ieea Reopened on my side

**Comment by KennyVaneetvelde** [comment]
@ieea How about when you try `mode=instructor.Mode.JSON`?

This is outside of the domain of Atomic Agents really, but this error happens in the underlying Instructor library

I had a look at similar issues and they seem to always refer to this: https://python.useinstructor.com/examples/ollama/?h=ollama#ollama

Does that help you along?

**Comment by KennyVaneetvelde** [comment]
Amazing! Thanks for letting me know!
